return {
    ["Animations de danses"] = {
        {label = "Danse 1", anim = "anim@amb@nightclub@dancers@podium_dancers@", animName = "hi_dance_facedj_17_v2_male^5", flag = 1},
        {label = "Danse 2", anim = "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@", animName = "high_center_down", flag = 1},
        {label = "Danse 3", anim = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", animName = "high_center", flag = 1},
        {label = "Danse 4", anim = "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@", animName = "high_center_up", flag = 1},
        {label = "Danse 5", anim = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", animName = "med_center", flag = 1},
        {label = "Danse 6", anim = "misschinese2_crystalmazemcs1_cs", animName = "dance_loop_tao", flag = 1},
        {label = "Danse 7", anim = "misschinese2_crystalmazemcs1_ig", animName = "dance_loop_tao", flag = 1},
        {label = "Danse 8", anim = "missfbi3_sniping", animName = "dance_m_default", flag = 1},
        {label = "Danse 9", anim = "rcmnigel1bnmt_1b", animName = "dance_loop_tyler", flag = 1},
        {label = "Danse 10", anim = "special_ped@mountain_dancer@monologue_3@monologue_3a", animName = "mnt_dnc_buttwag", flag = 1},
        {label = "Danse 11", anim = "anim@amb@casino@mini@dance@dance_solo@female@var_b@", animName = "high_center", flag = 1},
        {label = "Danse 12", anim = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", animName = "hi_dance_facedj_09_v2_female^3", flag = 1},
        {label = "Danse 13", anim = "timetable@tracy@ig_5@idle_a", animName = "idle_a", flag = 1},
        {label = "Danse 14", anim = "anim@amb@nightclub_island@dancers@crowddance_facedj@", animName = "mi_dance_facedj_17_v2_male^4", flag = 1},
        {label = "Danse 15", anim = "anim@amb@nightclub_island@dancers@crowddance_facedj@", animName = "mi_dance_facedj_15_v2_male^4", flag = 1},
        {label = "Danse 16", anim = "anim@amb@casino@mini@dance@dance_solo@female@var_b@", animName = "med_center", flag = 1},
        {label = "Danse 17", anim = "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@", animName = "low_center", flag = 1},     
        {label = "Danse 18", anim = "anim@amb@nightclub@dancers@crowddance_facedj@", animName = "hi_dance_facedj_13_v2_female^1", flag = 1}, 
        {label = "Danse 19", anim = "anim@amb@nightclub_island@dancers@crowddance_facedj@", animName = "hi_dance_facedj_17_v2_female^4", flag = 1},
        {label = "Danse 20", anim = "anim@amb@nightclub_island@dancers@beachdance@", animName = "mi_idle_c_m04", flag = 1, AnimationOptions = { EmoteLoop = true}},
        {label = "Danse 21", anim = "anim@amb@nightclub_island@dancers@beachdance@", animName = "mi_idle_c_m03", flag = 1, AnimationOptions = { EmoteLoop = true}},
        {label = "Danse 22", anim = "anim@amb@nightclub_island@dancers@beachdance@", animName = "mi_idle_c_m01", flag = 1, AnimationOptions = { EmoteLoop = true}},
        {label = "Danse 23", anim = "anim@amb@nightclub_island@dancers@beachdance@", animName = "hi_idle_c_m01", flag = 1, AnimationOptions = { EmoteLoop = true}},
        {label = "Danse 24", anim = "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@", animName = "high_center", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse 25", anim = "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@", animName = "high_center_down", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse 26", anim = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", animName = "med_center", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse 27", anim = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", animName = "low_center_up", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse 28", anim = "anim@amb@nightclub@dancers@crowddance_groups@", animName = "hi_dance_crowd_09_v1_female^1", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse 29", anim = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", animName = "low_center", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse 30", anim = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", animName = "med_center_up", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse 31", anim = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", animName = "med_right", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse 32", anim = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", animName = "high_left_up", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse 33", anim = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", animName = "hi_dance_facedj_09_v2_female^2", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse 34", anim = "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@", animName = "low_center_down", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse 35", anim = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", animName = "med_right_up", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse 36", anim = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", animName = "med_center_down", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse 37", anim = "anim@amb@nightclub@dancers@crowddance_facedj@", animName = "hi_dance_facedj_13_v2_female^2", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse 38", anim = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", animName = "high_center_down", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse 39", anim = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", animName = "low_center_up", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse 40", anim = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", animName = "high_left_up", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse 41", anim = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", animName = "high_right_up", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse 42", anim = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", animName = "med_left_up", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse 43", anim = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", animName = "low_left_up", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse 44", anim = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", animName = "hi_dance_facedj_09_v2_female^4", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse 45", anim = "anim@amb@nightclub@dancers@crowddance_groups@", animName = "hi_dance_crowd_09_v2_female^5", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse 46", anim = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", animName = "hi_dance_facedj_09_v2_male^5", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse F", anim = "anim@amb@nightclub@dancers@solomun_entourage@", animName = "mi_dance_facedj_17_v1_female^1", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse F2", anim = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", animName = "high_center", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse F3", anim = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", animName = "high_center_up", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse F4", anim = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", animName = "hi_dance_facedj_09_v2_female^1", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse F5", anim = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", animName = "hi_dance_facedj_09_v2_female^3", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse F6", anim = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", animName = "high_center_up", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse F7", anim = "mini@strip_club@lap_dance_2g@ld_2g_p2", animName = "ld_2g_p2_s2", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse F8", anim = "anim@amb@nightclub_island@dancers@crowddance_single_props@", animName = "hi_dance_prop_11_v1_female^3", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse F9", anim = "anim@amb@nightclub_island@dancers@crowddance_single_props@", animName = "hi_dance_prop_09_v1_male^3", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse F10", anim = "anim@amb@nightclub_island@dancers@crowddance_single_props@", animName = "hi_dance_prop_11_v1_female^1", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse Slow 2", anim = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", animName = "low_center", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse Slow 3", anim = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", animName = "low_center_down", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse Slow 4", anim = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", animName = "low_center", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse Slow 5", anim = "anim@amb@nightclub@dancers@crowddance_groups_transitions@from_med_intensity", animName = "trans_dance_crowd_mi_to_li_09_v2_female^5", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse Slow 6", anim = "anim@amb@nightclub@dancers@crowddance_groups_transitions@from_med_intensity", animName = "trans_dance_crowd_li_to_hi_09_v1_male^1", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse Silly", anim = "move_clown@p_m_zero_idles@", animName = "fidget_short_dance", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse Silly 2", anim = "move_clown@p_m_two_idles@", animName = "fidget_short_dance", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse Silly 3", anim = "move_clown@p_m_zero_idles@", animName = "fidget_short_dance", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse Glowsticks", anim = "anim@amb@nightclub@lazlow@hi_railing@", animName = "ambclub_13_mi_hi_sexualgriding_laz", flag = 1, AnimationOptions = { EmoteLoop = true}},
        {label = "Danse Glowsticks 2", anim = "anim@amb@nightclub@lazlow@hi_railing@", animName = "ambclub_09_mi_hi_bellydancer_laz", flag = 1},        
        {label = "Danse Horse", anim = "anim@amb@nightclub@lazlow@hi_dancefloor@", animName = "dancecrowd_li_15_handup_laz", flag = 1, AnimationOptions = { EmoteLoop = true}},
        {label = "Danse Sexy", anim = "mini@strip_club@lap_dance_2g@ld_2g_p1", animName = "ld_2g_p1_s2", flag = 1, AnimationOptions = { EmoteLoop = true}},
        {label = "Danse Sexy 2", anim = "mini@strip_club@private_dance@part2", animName = "priv_dance_p2", flag = 1, AnimationOptions = { EmoteLoop = true}},
        {label = "Danse Sexy 3", anim = "mp_safehouse", animName = "lap_dance_girl", flag = 1, AnimationOptions = { EmoteLoop = true}},
        {label = "Danse Sexy 4", anim = "mini@strip_club@private_dance@part1", animName = "priv_dance_p1", flag = 1, AnimationOptions = { EmoteLoop = true}},
        {label = "Danse Sexy 5", anim = "mini@strip_club@lap_dance@ld_girl_a_song_a_p1", animName = "ld_girl_a_song_a_p1_f", flag = 1, AnimationOptions = { EmoteLoop = true}},
        {label = "Danse Excité", anim = "anim@amb@nightclub@mini@dance@dance_solo@jumper@", animName = "high_left_up", flag = 1, AnimationOptions = { EmoteLoop = true}},
        {label = "Danse DJ", anim = "anim@amb@nightclub@djs@dixon@", animName = "dixn_dance_cntr_open_dix", flag = 1, AnimationOptions = { EmoteLoop = true}},
        {label = "Danse DJ 2", anim = "anim@amb@nightclub@djs@dixon@", animName = "dixn_end_dix", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse DJ 3", anim = "anim@amb@nightclub@djs@solomun@", animName = "sol_idle_ctr_mid_a_sol", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse avec Bras", anim = "anim@amb@nightclub_island@dancers@beachdance@", animName = "mi_idle_b_m02", flag = 1, AnimationOptions = { EmoteLoop = true}},
        {label = "Danse avec Bras 2", anim = "anim@amb@nightclub_island@dancers@beachdance@", animName = "mi_idle_c_m02", flag = 1, AnimationOptions = { EmoteLoop = true}},
        {label = "Danse Bras Levés", anim = "anim@amb@nightclub_island@dancers@beachdance@", animName = "mi_idle_c_m05", flag = 1, AnimationOptions = { EmoteLoop = true}},
        {label = "Danse Bras Levés 2", anim = "anim@amb@nightclub_island@dancers@beachdance@", animName = "hi_idle_c_m03", flag = 1, AnimationOptions = { EmoteLoop = true}},
        {label = "Danse Bras Levés 3", anim = "anim@amb@nightclub@dancers@crowddance_facedj@", animName = "hi_dance_facedj_11_v2_male^5", flag = 1, AnimationOptions = { EmoteLoop = true}},
        {label = "Danse Bras Levés 4", anim = "anim@amb@nightclub_island@dancers@beachdance@", animName = "hi_idle_c_m02", flag = 1, AnimationOptions = { EmoteLoop = true}},
        {label = "Danse Clown", anim = "anim@amb@nightclub@mini@dance@dance_solo@techno_monkey@", animName = "high_center_down", flag = 1, AnimationOptions = { EmoteLoop = true}},
        {label = "Danse Salsa", anim = "anim@amb@nightclub@mini@dance@dance_paired@dance_h@", animName = "ped_b_dance_idle", flag = 1, AnimationOptions = { EmoteLoop = true}},
        {label = "Danse Poisson", anim = "anim@mp_player_intupperfind_the_fish", animName = "idle_a", flag = 1, AnimationOptions = {EmoteLoop = true, EmoteMoving = true}},
        {label = "Danse Boxe Solo", anim = "anim@amb@nightclub@mini@dance@dance_solo@beach_boxing@", animName = "med_right_down", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse Crank Dat", anim = "anim@amb@nightclub@mini@dance@dance_solo@shuffle@", animName = "high_right_up", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse Crank Dat 2", anim = "anim@amb@nightclub@mini@dance@dance_solo@shuffle@", animName = "high_right_down", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse Hip Hop 1", anim = "anim@amb@nightclub@mini@dance@dance_paired@dance_d@", animName = "ped_a_dance_idle", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse Hip Hop 2", anim = "anim@amb@nightclub@mini@dance@dance_paired@dance_b@", animName = "ped_a_dance_idle", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse Hip Hop 3", anim = "anim@amb@nightclub@mini@dance@dance_paired@dance_a@", animName = "ped_a_dance_idle", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse Vieux", anim = "anim@mp_player_intupperuncle_disco", animName = "idle_a", flag = 1, AnimationOptions = { EmoteLoop = true }},
        {label = "Danse Timide", anim = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", animName = "low_center_down", flag = 1, AnimationOptions = { EmoteLoop = true }},
    },
   ["Animations"] = {
        ["🧰 Professionnels"] = {
            {label = "Police : Bras croisés", anim = "anim@amb@nightclub@peds@", animName = "rcmme_amanda1_stand_loop_cop", flag = 1},
            {label = "Police : Direction", anim = "amb@world_human_car_park_attendant@male@base", animName = "base", flag = 1},
            {label = "Police : Radio", anim = "amb@code_human_police_investigate@idle_a", animName = "idle_b", flag = 1},
            {label = "Mécanicien : Réparer", anim = "mini@repair", animName = "fixing_a_player", flag = 1},
            {label = "EMS : Vérifier le patient", anim = "amb@code_human_police_investigate@idle_b", animName = "idle_f", flag = 1},
            {label = "EMS : Réanimer", anim = "mini@cpr@char_a@cpr_str", animName = "cpr_pumpchest", flag = 1, AnimationOptions = {EmoteLoop = true}},
            {label = "EMS : S'accroupir", anim = "amb@medic@standing@tendtodead@base", animName = "base", flag = 1},
            {label = "EMS : S'accroupir 2", anim = "amb@medic@standing@kneel@idle_a", animName = "idle_a", flag = 1},
            {label = "Agriculteur : Planter", anim = "anim@amb@business@coc@coc_unpack_cut@", animName = "fullcut_cycle_v6_cokecutter", flag = 1},
            {label = "Bartender", anim = "anim@amb@clubhouse@bar@drink@idle_a", animName = "idle_a_bartender", flag = 1, AnimationOptions = {EmoteLoop = true, EmoteMoving = true}},
        },
        ["⚽️ Sports"] = {
            {label = "Pompes", anim = "amb@world_human_push_ups@male@base", animName = "base", flag = 1},
            {label = "Abdos", anim = "amb@world_human_sit_ups@male@base", animName = "base", flag = 1},
            {label = "Yoga", anim = "amb@world_human_yoga@male@base", animName = "base_a", flag = 1},
            {label = "S'étirer", anim = "rcmfanatic1maryann_stretchidle_b", animName = "idle_e", flag = 0},
            {label = "S'étirer 2", anim = "anim@deathmatch_intros@unarmed", animName = "intro_male_unarmed_c", flag = 0},
            {label = "S'étirer 3", anim = "mini@triathlon", animName = "idle_e", flag = 1, AnimationOptions = {EmoteLoop = true}},
            {label = "S'étirer 4", anim = "mini@triathlon", animName = "idle_f", flag = 1, AnimationOptions = {EmoteLoop = true}},
            {label = "S'étirer 5", anim = "mini@triathlon", animName = "idle_d", flag = 1, AnimationOptions = {EmoteLoop = true}},
            {label = "Barre de traction", anim = "amb@prop_human_muscle_chin_ups@male@base", animName = "base", flag = 1},
            {label = "Flexion", anim = "amb@world_human_muscle_flex@arms_at_side@base", animName = "base", flag = 1},
            {label = "Jumping Jacks", anim = "timetable@reunited@ig_2", animName = "jimmy_getknocked", flag = 1},
            {label = "Boxer", anim = "anim@mp_player_intcelebrationmale@shadow_boxing", animName = "shadow_boxing", flag = 0},
        },
        ["🔵 Gangs"] = {
            {label = "Marabunta", anim = "mp_player_int_uppergang_sign_a", animName = "mp_player_int_gang_sign_a", flag = 49},
            {label = "Ballas", anim = "mp_player_int_uppergang_sign_b", animName = "mp_player_int_gang_sign_b", flag = 49},
            {label = "Ballas 2", anim = "amb@code_human_in_car_mp_actions@gang_sign_b@low@ps@base", animName = "idle_a", flag = 49},
            {label = "Ballas 3", anim = "amb@code_human_in_car_mp_actions@v_sign@std@rds@base", animName = "idle_a", flag = 49},
            {label = "Gang 1", anim = "mp_player_int_upperv_sign", animName = "mp_player_int_v_sign", flag = 49},
        },
        {label = "Salut", anim = "gestures@m@standing@casual", animName = "gesture_hello", flag = 48},
        {label = "Au revoir", anim = "gestures@f@standing@casual", animName = "gesture_bye_soft", flag = 48},
        {label = "Hochement de tête", anim = "gestures@f@standing@casual", animName = "gesture_nod_yes_soft", flag = 48},
        {label = "Secouer la tête", anim = "gestures@f@standing@casual", animName = "gesture_nod_no_soft", flag = 48},
        {label = "Poignée de main", anim = "mp_common", animName = "givetake1_a", flag = 0},
        {label = "Accolade", anim = "mp_ped_interaction", animName = "kisses_guy_a", flag = 0},
        {label = "Serrer les poings", anim = "anim@mp_player_intcelebrationmale@bro_love", animName = "bro_love", flag = 48},
        {label = "Blow Kiss", anim = "anim@mp_player_intcelebrationfemale@blow_kiss", animName = "blow_kiss", flag = 48},
        {label = "Blow Kiss 2", anim = "anim@mp_player_intselfieblow_kiss", animName = "exit", flag = 48, AnimationOptions = {EmoteMoving = true, EmoteDuration = 2000}},
        {label = "Applaudir", anim = "anim@mp_player_intupperslow_clap", animName = "idle_a", flag = 49},
        {label = "Applaudir 2", anim = "amb@world_human_cheering@male_a", animName = "base", flag = 49},
        {label = "Applaudir Lentement", anim = "anim@mp_player_intcelebrationfemale@slow_clap", animName = "slow_clap", flag = 49},
        {label = "Siffler", anim = "rcmnigel1c", animName = "hailing_whistle_waive_a", flag = 48},
        {label = "Pouce en l'air", anim = "anim@mp_player_intupperthumbs_up", animName = "idle_a", flag = 48},
        {label = "Salut militaire", anim = "anim@mp_player_intuppersalute", animName = "idle_a", flag = 48},
        {label = "Bras croisés", anim = "amb@world_human_hang_out_street@male_c@base", animName = "base", flag = 1},
        {label = "Lever les mains", anim = "random@mugging3", animName = "handsup_standing_base", flag = 49},
        {label = "S'asseoir sur chaise", anim = "anim@heists@prison_heistunfinished_biztarget_idle", animName = "target_idle", flag = 1},
        {label = "Surrender", anim = "random@arrests@busted", animName = "idle_a", flag = 1, AnimationOptions = {EmoteLoop = true}},
        {label = "Surrender 2", anim = "random@arrests", animName = "kneeling_arrest_idle", flag = 1, AnimationOptions = {EmoteLoop = true}},
        {label = "Surrender 3", anim = "mp_bank_heist_1", animName = "m_cower_01", flag = 1, AnimationOptions = {EmoteLoop = true, ExitEmote = "getup", ExitEmoteType = "Exits"}},
        {label = "Surrender 4", anim = "mp_bank_heist_1", animName = "m_cower_02", flag = 1, AnimationOptions = {EmoteLoop = true, ExitEmote = "getup", ExitEmoteType = "Exits"}},
        {label = "Surrender 5", anim = "random@arrests", animName = "kneeling_arrest_idle", flag = 1, AnimationOptions = {EmoteLoop = true, ExitEmote = "surrender_exit", ExitEmoteType = "Exits"}},
        {label = "Surrender 6", anim = "rcmbarry", animName = "m_cower_01", flag = 1, AnimationOptions = {EmoteLoop = true, ExitEmote = "getup", ExitEmoteType = "Exits"}},
        {label = "Facepalm 2", anim = "anim@mp_player_intcelebrationfemale@face_palm", animName = "face_palm", flag = 48, AnimationOptions = {EmoteMoving = true, EmoteDuration = 8000}},
        {label = "Facepalm 3", anim = "missminuteman_1ig_2", animName = "tasered_2", flag = 48, AnimationOptions = {EmoteMoving = true, EmoteDuration = 8000}},
        {label = "Facepalm 4", anim = "anim@mp_player_intupperface_palm", animName = "idle_a", flag = 48, AnimationOptions = {EmoteMoving = true, EmoteLoop = true}},
        {label = "Tomber ", anim = "random@drunk_driver_1", animName = "drunk_fall_over", flag = 0},
        {label = "Tomber  2", anim = "mp_suicide", animName = "pistol", flag = 0},
        {label = "Tomber  3", anim = "mp_suicide", animName = "pill", flag = 0},
        {label = "Tomber  4", anim = "friends@frf@ig_2", animName = "knockout_plyr", flag = 0},
        {label = "Tomber  5", anim = "anim@gangops@hostage@", animName = "victim_fail", flag = 0},
        {label = "Toi", anim = "gestures@f@standing@casual", animName = "gesture_point", flag = 48, AnimationOptions = {EmoteLoop = true, EmoteMoving = true}},
        {label = "Drink", anim = "mp_player_inteat@pnq", animName = "loop", flag = 48, AnimationOptions = {EmoteMoving = true, EmoteDuration = 2500}},
        {label = "Rire", anim = "anim@arena@celeb@flat@paired@no_props@", animName = "laugh_a_player_a", flag = 48},
        {label = "Facepalm", anim = "anim@mp_player_intupperface_palm", animName = "idle_a", flag = 48},
        {label = "Ennuyé", anim = "amb@world_human_hang_out_street@female_hold_arm@enter", animName = "enter", flag = 1},
        {label = "Air Guitar", anim = "anim@mp_player_intcelebrationmale@air_guitar", animName = "air_guitar", flag = 49},
        {label = "Bouche bée", anim = "anim@mp_player_intcelebrationmale@face_palm", animName = "face_palm", flag = 48},
        {label = "Chut", anim = "anim@mp_player_intuppershush", animName = "idle_a", flag = 48},
        {label = "Idle Drunk", anim = "random@drunk_driver_1", animName = "drunk_driver_stand_loop_dd1", flag = 49, AnimationOptions = {EmoteLoop = true}},
        {label = "Jazz Hands", anim = "anim@mp_player_intcelebrationmale@jazz_hands", animName = "jazz_hands", flag = 49},
        {label = "Gangnam Style", anim = "anim@mp_player_intcelebrationfemale@the_woogie", animName = "the_woogie", flag = 49},
        {label = "Signe de paix", anim = "mp_player_int_upperpeace_sign", animName = "mp_player_int_peace_sign", flag = 48},
        {label = "Doigt d'honneur", anim = "anim@mp_player_intselfiethe_bird", animName = "idle_a", flag = 48},
        {label = "Peur", anim = "amb@code_human_cower_stand@female@idle_a", animName = "idle_c", flag = 49},
        {label = "Air Synth", anim = "anim@mp_player_intcelebrationfemale@air_synth", animName = "air_synth", flag = 48},
        {label = "Naruto pose", anim = "missfbi1", animName = "ledge_loop", flag = 1},
        {label = "Attendre", anim = "misshair_shop@hair_dressers", animName = "keeper_base", flag = 1},
        {label = "Bras croisés 2", anim = "anim@amb@nightclub@peds@", animName = "rcmme_amanda1_stand_loop_cop", flag = 1},
        {label = "Attendre F", anim = "anim@amb@nightclub@peds@", animName = "amb_world_human_hang_out_street_female_hold_arm_idle_b", flag = 1},
        {label = "Attendre 2 F", anim = "amb@world_human_smoking@female@idle_a", animName = "idle_b", flag = 1},
        {label = "Poser Comptoir", anim = "amb@prop_human_bum_shopping_cart@male@idle_a", animName = "idle_c", flag = 1},
        {label = "Poser contre un mur", anim = "amb@world_human_leaning@female@wall@back@holding_elbow@idle_a", animName = "idle_a", flag = 1},
        {label = "S'accroupir", anim = "amb@world_human_bum_wash@male@low@idle_a", animName = "idle_a", flag = 1},
        {label = "Montrer ses fesses", anim = "switch@trevor@mocks_lapdance", animName = "001443_01_trvs_28_idle_stripper", flag = 1},
        {label = "Faire la poule", anim = "random@peyote@chicken", animName = "wakeup", flag = 1},
        {label = "Pourquoi", anim = "anim@mp_player_intcelebrationfemale@face_palm", animName = "face_palm", flag = 1},
        {label = "Célébrer", anim = "misscommon@response", animName = "bring_it_on", flag = 1},
        {label = "S'asseoir", anim = "anim@heists@fleeca_bank@ig_7_jetski_owner", animName = "owner_idle", flag = 1},
        {label = "S'asseoir 2", anim = "anim@amb@business@bgen@bgen_no_work@", animName = "sit_phone_phoneputdown_idle_nowork", flag = 1},
        {label = "S'asseoir contre mur", anim = "timetable@jimmy@mics3_ig_15@", animName = "idle_a_jimmy", flag = 1},
        {label = "S'asseoir F", anim = "amb@lo_res_idles@", animName = "world_human_picnic_female_lo_res_base", flag = 1},
        {label = "S'asseoir chaise", anim = "missheist_jewelleadinout", animName = "jh_int_outro_loop_a", flag = 1},
        {label = "S'asseoir chaise 2", anim = "timetable@maid@couch@", animName = "base", flag = 1},
        {label = "S'asseoir Chaise 3", anim = "timetable@ron@ig_5_p3", animName = "ig_5_p3_base", flag = 1},
        {label = "Tu veux quoi ?", anim = "mini@triathlon", animName = "want_some_of_this", flag = 0},
        {label = "Enerver", anim = "anim@amb@casino@brawl@fights@argue@", animName = "arguement_loop_mp_m_brawler_02", flag = 0},
        {label = "Oiseau", anim = "random@peyote@bird", animName = "wakeup", flag = 0},
        {label = "Appeler chien", anim = "missfra0_chop_find", animName = "call_chop_l", flag = 0},
        {label = "Faire le mort", anim = "missarmenian2", animName = "drunk_loop", flag = 1},
        {label = "S'allonger", anim = "amb@world_human_sunbathe@female@back@base", animName = "base", flag = 1},
        {label = "S'allonger 2", anim = "switch@trevor@annoys_sunbathers", animName = "trev_annoys_sunbathers_loop_guy", flag = 1},
        {label = "Dormir", anim = "anim@amb@nightclub@lazlow@lo_sofa@", animName = "lowsofa_base_laz", flag = 1},
        {label = "Kick", anim = "melee@unarmed@streamed_core", animName = "kick_close_a", flag = 0},
        {label = "Respect", anim = "anim@mp_player_intcelebrationmale@respect", animName = "respect", flag = 0},
        {label = "Attendre 1", anim = "timetable@amanda@ig_2", animName = "ig_2_base_amanda", flag = 1, AnimationOptions = {EmoteLoop = true, EmoteMoving = true}},
        {label = "Attendre 2", anim = "rcmnigel1cnmt_1c", animName = "base", flag = 1, AnimationOptions = {EmoteLoop = true, EmoteMoving = true}},
        {label = "Attendre 3", anim = "rcmjosh1", animName = "idle", flag = 1, AnimationOptions = {EmoteLoop = true, EmoteMoving = true}},
        {label = "Slap", anim = "melee@unarmed@streamed_variations", animName = "plyr_takedown_front_slap", flag = 1, AnimationOptions = {EmoteLoop = true, EmoteMoving = true, EmoteDuration = 2000}},
        {label = "Headbutt", anim = "melee@unarmed@streamed_variations", animName = "plyr_takedown_front_headbutt", flag = 1},
        {label = "Peace", anim = "mp_player_int_upperpeace_sign", animName = "mp_player_int_peace_sign", flag = 1, AnimationOptions = {EmoteLoop = true, EmoteMoving = true}},
        {label = "Peace 2", anim = "anim@mp_player_intupperpeace", animName = "idle_a", flag = 1, AnimationOptions = {EmoteLoop = true, EmoteMoving = true}},
        {label = "Peace 3", anim = "anim@mp_player_intupperpeace", animName = "idle_a_fp", flag = 1, AnimationOptions = {EmoteLoop = true, EmoteMoving = true}},
        {label = "Peace 4", anim = "anim@mp_player_intincarpeacestd@ds@", animName = "idle_a", flag = 1, AnimationOptions = {EmoteLoop = true, EmoteMoving = true}},
        {label = "Peace 5", anim = "anim@mp_player_intincarpeacestd@ds@", animName = "idle_a_fp", flag = 1, AnimationOptions = {EmoteLoop = true, EmoteMoving = true}},
        {label = "Peace 6", anim = "anim@mp_player_intincarpeacebodhi@ds@", animName = "idle_a", flag = 1, AnimationOptions = {EmoteLoop = true, EmoteMoving = true}},
        {label = "Peace 7", anim = "anim@mp_player_intincarpeacebodhi@ds@", animName = "idle_a_fp", flag = 1, AnimationOptions = {EmoteLoop = true, EmoteMoving = true}},
        {label = "Peace Female", anim = "anim@mp_player_intcelebrationfemale@peace", animName = "peace", flag = 1, AnimationOptions = {EmoteLoop = true, EmoteMoving = true}},
        {label = "Espionner", anim = "random@paparazzi@peek", animName = "left_peek_a", flag = 1, AnimationOptions = {EmoteLoop = true}},
        {label = "Tousser", anim = "timetable@gardener@smoking_joint", animName = "idle_cough", flag = 1, AnimationOptions = {EmoteLoop = true, EmoteMoving = true}},
        {label = "Celebrate", anim = "rcmfanatic1celebrate", animName = "celebrate", flag = 1, AnimationOptions = {EmoteLoop = true}},
        {label = "Superhero", anim = "rcmbarry", animName = "base", flag = 1, AnimationOptions = {EmoteLoop = true}},
        {label = "Mind Control", anim = "rcmbarry", animName = "mind_control_b_loop", flag = 1, AnimationOptions = {EmoteLoop = true}},
        {label = "Mind Control 2", anim = "rcmbarry", animName = "bar_1_attack_idle_aln", flag = 1, AnimationOptions = {EmoteLoop = true}},
        {label = "Clown", anim = "rcm_barry2", animName = "clown_idle_0", flag = 1, AnimationOptions = {EmoteLoop = true}},
        {label = "Clown 2", anim = "rcm_barry2", animName = "clown_idle_1", flag = 1, AnimationOptions = {EmoteLoop = true}},
        {label = "Clown 3", anim = "rcm_barry2", animName = "clown_idle_2", flag = 1, AnimationOptions = {EmoteLoop = true}},
        {label = "Clown 4", anim = "rcm_barry2", animName = "clown_idle_3", flag = 1, AnimationOptions = {EmoteLoop = true, EmoteMoving = true}},
        {label = "Clown 5", anim = "rcm_barry2", animName = "clown_idle_6", flag = 1, AnimationOptions = {EmoteLoop = true}},
        {label = "Try Clothes F", anim = "mp_clothing@female@trousers", animName = "try_trousers_neutral_a", flag = 1, AnimationOptions = {EmoteLoop = true}},
        {label = "Try Clothes 2 F", anim = "mp_clothing@female@shirt", animName = "try_shirt_positive_a", flag = 1, AnimationOptions = {EmoteLoop = true}},
        {label = "Try Clothes 3 F", anim = "mp_clothing@female@shoes", animName = "try_shoes_positive_a", flag = 1, AnimationOptions = {EmoteLoop = true}},
        {label = "Try Clothes 4 F", anim = "anim@scripted@ulp_missions@change_clothes@female@", animName = "change_highroller", flag = 1},
        {label = "Try Clothes 5 F", anim = "anim@scripted@ulp_missions@change_clothes@", animName = "change_highroller_male", flag = 1},
    },
    ["Props animations"] = {
        {label = "Boire un café", anim = "amb@world_human_aa_coffee@idle_a", animName = "idle_a", flag = 49, props = {
            {model = "p_amb_coffeecup_01", bone = 28422, coords = {x = 0.0, y = 0.0, z = 0.0}, rotation = {x = 0.0, y = 0.0, z = 0.0}}
        }},
        {label = "Fumer une cigarette", anim = "amb@world_human_smoking@male@male_a@enter", animName = "enter", flag = 49, props = {
            {model = "prop_amb_ciggy_01", bone = 28422, coords = {x = 0.009, y = 0.0, z = 0.0}, rotation = {x = 0.0, y = 0.0, z = 0.0}}
        }},
        {label = "Bloc-notes", anim = "missheistdockssetup1clipboard@base", animName = "base", flag = 49, props = {
            {model = "prop_notepad_01", bone = 18905, coords = {x = 0.1, y = 0.02, z = 0.05}, rotation = {x = 10.0, y = 0.0, z = 0.0}}
        }},
        {label = "Parapluie", anim = "amb@world_human_drinking@coffee@male@base", animName = "base", flag = 49, props = {
            {model = "p_amb_brolly_01", bone = 57005, coords = {x = 0.15, y = 0.005, z = 0.0}, rotation = {x = 87.0, y = -20.0, z = 180.0}}
        }, AnimationOptions = {EmoteLoop = true, EmoteMoving = true}},
        {label = "Carton", anim = "anim@heists@box_carry@", animName = "idle", flag = 49, props = {
            {model = "hei_prop_heist_box", bone = 60309, coords = {x = 0.025, y = 0.08, z = 0.255}, rotation = {x = -145.0, y = 290.0, z = 0.0}}
        }, AnimationOptions = {EmoteLoop = true, EmoteMoving = true}},
        {label = "Rose", anim = "anim@heists@humane_labs@finale@keycards", animName = "ped_a_enter_loop", flag = 49, props = {
            {model = "prop_single_rose", bone = 18905, coords = {x = 0.13, y = 0.15, z = 0.0}, rotation = {x = -100.0, y = 0.0, z = -20.0}}
        }, AnimationOptions = {EmoteLoop = true, EmoteMoving = true}},
        {label = "Joint", anim = "amb@world_human_smoking@male@male_a@enter", animName = "enter", flag = 49, props = {
            {model = "p_cs_joint_02", bone = 47419, coords = {x = 0.015, y = -0.009, z = 0.003}, rotation = {x = 55.0, y = 0.0, z = 110.0}}
        }, AnimationOptions = {EmoteMoving = true, EmoteDuration = 2600}},
        {label = "Pluie de billets", anim = "anim@mp_player_intupperraining_cash", animName = "idle_a", flag = 49, prop = "prop_anim_cash_pile_01", propBone = 60309, propCoords = {x = 0.0, y = 0.0, z = 0.0}, propRot = {x = 180.0, y = 0.0, z = 70.0}, AnimationOptions = {EmoteLoop = true, EmoteMoving = true}},
        {label = "Tablette", anim = "amb@world_human_tourist_map@male@base", animName = "base", flag = 49, prop = "prop_cs_tablet", propBone = 28422, propCoords = {x = 0.0, y = -0.03, z = 0.0}, propRot = {x = 20.0, y = -90.0, z = 0.0}, AnimationOptions = {EmoteLoop = true, EmoteMoving = true}},
        {label = "Nettoyer", anim = "timetable@floyd@clean_kitchen@base", animName = "base", flag = 49, prop = "prop_sponge_01", propBone = 28422, propCoords = {x = 0.0, y = 0.0, z = -0.01}, propRot = {x = 90.0, y = 0.0, z = 0.0}, AnimationOptions = {EmoteLoop = true, EmoteMoving = true}},
        {label = "Appareil photo", anim = "amb@world_human_paparazzi@male@base", animName = "base", flag = 49, props = {
            {model = "prop_pap_camera_01", bone = 28422, coords = {x = 0.0, y = 0.0, z = 0.0}, rotation = {x = 0.0, y = 0.0, z = 0.0}}
        }, AnimationOptions = {EmoteLoop = true, EmoteMoving = true}},
        {label = "Serveur", anim = "anim@move_f@waitress", animName = "idle", flag = 49, props = {
            {model = "prop_plate_01", bone = 28422, coords = {x = 0.0, y = 0.0, z = 0.0}, rotation = {x = 0.0, y = 0.0, z = 0.0}},
            {model = "prop_wine_bot_01", bone = 60309, coords = {x = 0.0, y = 0.0, z = 0.0}, rotation = {x = 0.0, y = 0.0, z = 0.0}}
        }, AnimationOptions = {EmoteLoop = true, EmoteMoving = true}},
        {label = "Boire une bière", anim = "amb@world_human_drinking@beer@male@base", animName = "base", flag = 49, props = {
            {model = "prop_amb_beer_bottle", bone = 28422, coords = {x = 0.0, y = 0.0, z = 0.0}, rotation = {x = 0.0, y = 0.0, z = 0.0}}
        }, AnimationOptions = {EmoteLoop = true, EmoteMoving = true}},
        {label = "Bouteille d'eau", anim = "amb@world_human_drinking@beer@male@base", animName = "base", flag = 49, props = {
            {model = "prop_ld_flow_bottle", bone = 28422, coords = {x = 0.0, y = 0.0, z = 0.0}, rotation = {x = 0.0, y = 0.0, z = 0.0}}
        }, AnimationOptions = {EmoteLoop = true, EmoteMoving = true}},
        {label = "Guitariste", anim = "amb@world_human_musician@guitar@male@base", animName = "base", flag = 49, props = {
            {model = "prop_acc_guitar_01", bone = 24818, coords = {x = -0.1, y = 0.31, z = 0.1}, rotation = {x = -0.05, y = 20.0, z = 150.0}},
            {model = "prop_cs_sol_glasses", bone = 31086, coords = {x = 0.0, y = 0.0, z = 0.0}, rotation = {x = 0.0, y = 0.0, z = 0.0}}
        }, AnimationOptions = {EmoteLoop = true, EmoteMoving = true}},
    },
    ["Humeurs"] = {
        {label = "Heureux", mood = "mood_happy_1"},
        {label = "En colère", mood = "mood_angry_1"},
        {label = "Stupéfait", mood = "mood_stressed_1"},
        {label = "Dormeur", mood = "mood_sleeping_1"},
        {label = "Blessé", mood = "mood_injured_1"},
        {label = "Électrique", mood = "electrocuted_1"},
        {label = "Bourré", mood = "mood_drunk_1"},
        {label = "Abruti", mood = "pose_injured_1"},
        {label = "Grincheux", mood = "effort_1"},
        {label = "Grincheux 2", mood = "mood_drivefast_1"},
        {label = "Grincheux 3", mood = "pose_angry_1"},
        {label = "Joyeux", mood = "mood_dancing_low_1"},
        {label = "Respirateur buccal", mood = "smoking_hold_1"},
        {label = "Ne cligne jamais", mood = "pose_normal_1"},
        {label = "Un œil", mood = "pose_aiming_1"},
        {label = "Choqué", mood = "shocked_1"},
        {label = "Choqué 2", mood = "shocked_2"},
        {label = "Dormeur 2", mood = "dead_1"},
        {label = "Dormeur 3", mood = "dead_2"},
        {label = "Suffisant", mood = "mood_smug_1"},
        {label = "Spéculatif", mood = "mood_aiming_1"},
        {label = "Stressé", mood = "mood_stressed_1"},
        {label = "Boudeur", mood = "mood_sulk_1"},
        {label = "Bizarre", mood = "effort_2"},
        {label = "Bizarre 2", mood = "effort_3"},
    },
    ["Démarches"] = {
        {label = "Normal H", walk = "move_m@multiplayer"},
        {label = "Normal F", walk = "move_f@multiplayer"},
        {label = "Alien", walk = "move_m@alien"},
        {label = "Blindé", walk = "anim_group_move_ballistic"},
        {label = "Arrogant", walk = "move_f@arrogant@a"},
        {label = "Brave", walk = "move_m@brave"},
        {label = "Décontractée", walk = "move_m@casual@a"},
        {label = "Décontractée 2", walk = "move_m@casual@b"},
        {label = "Décontractée 3", walk = "move_m@casual@c"},
        {label = "Décontractée 4", walk = "move_m@casual@d"},
        {label = "Décontractée 5", walk = "move_m@casual@e"},
        {label = "Décontractée 6", walk = "move_m@casual@f"},
        {label = "Chichi", walk = "move_f@chichi"},
        {label = "Confiante", walk = "move_m@confident"},
        {label = "Police", walk = "move_m@business@a"},
        {label = "Police 2", walk = "move_m@business@b"},
        {label = "Police 3", walk = "move_m@business@c"},
        {label = "Bourré", walk = "move_m@drunk@a"},
        {label = "Bourré 2", walk = "move_m@drunk@slightlydrunk"},
        {label = "Bourré 3", walk = "move_m@buzzed"},
        {label = "Bourré 4", walk = "move_m@drunk@verydrunk"},
        {label = "Féminine", walk = "move_f@femme@"},
        {label = "En feu", walk = "move_characters@franklin@fire"},
        {label = "En feu 2", walk = "move_characters@michael@fire"},
        {label = "En feu 3", walk = "move_m@fire"},
        {label = "Franklin", walk = "move_p_m_one"},
        {label = "Gangster", walk = "move_m@gangster@generic"},
        {label = "Gangster 2", walk = "move_m@gangster@ng"},
        {label = "Gangster 3", walk = "move_m@gangster@var_e"},
        {label = "Gangster 4", walk = "move_m@gangster@var_i"},
        {label = "Gangster Triste", walk = "move_m@gangster@var_f"},
        {label = "Grooving", walk = "anim@move_m@grooving@"},
        {label = "Garde", walk = "move_m@prison_gaurd"},
        {label = "Menotté", walk = "move_m@prisoner_cuffed"},
        {label = "Talons", walk = "move_f@heels@c"},
        {label = "Talons 2", walk = "move_f@heels@d"},
        {label = "Randonnée", walk = "move_m@hiking"},
        {label = "Hipster", walk = "move_m@hipster@a"},
        {label = "Clochard", walk = "move_m@hobo@a"},
        {label = "Pressé", walk = "move_f@hurry@a"},
        {label = "Colère", walk = "move_p_m_zero_janitor"},
        {label = "Colère 2", walk = "move_p_m_zero_slow"},
        {label = "Jogging", walk = "move_m@jog@"},
        {label = "Lemar", walk = "anim_group_move_lemar_alley"},
        {label = "Lester", walk = "move_heist_lester"},
        {label = "Lester 2", walk = "move_lester_caneup"},
        {label = "Mangeuse d'hommes", walk = "move_f@maneater"},
        {label = "Michael", walk = "move_ped_bucket"},
        {label = "Argent", walk = "move_m@money"},
        {label = "Musclé", walk = "move_m@muscle@a"},
        {label = "Posh", walk = "move_m@posh@"},
        {label = "Posh 2", walk = "move_f@posh@"},
        {label = "Rapide", walk = "move_m@quick"},
        {label = "Coureur F", walk = "female_fast_runner"},
        {label = "Triste", walk = "move_m@sad@a"},
        {label = "Sassy", walk = "move_m@sassy"},
        {label = "Sassy 2", walk = "move_f@sassy"},
        {label = "Peur", walk = "move_f@scared"},
        {label = "Sexy", walk = "move_f@sexy@a"},
        {label = "Ombreux", walk = "move_m@shadyped@a"},
        {label = "Lent", walk = "move_characters@jimmy@slow@"},
        {label = "Swagger", walk = "move_m@swagger"},
        {label = "Dur M", walk = "move_m@tough_guy@"},
        {label = "Dur F", walk = "move_f@tough_guy@"},
        {label = "Éboueur", walk = "clipset@move@trash_fast_turn"},
        {label = "Éboueur 2", walk = "missfbi4prepp1_garbageman"},
        {label = "Trevor", walk = "move_p_m_two"},
        {label = "Large", walk = "move_m@bag"},
    }
}